### PR TITLE
Update versionfix to make it work again

### PR DESCRIPTION
**Pull request by gamma**
There are several changes that needed to be done:

  * There was a missing dependency, which I updated.
  * The DW URLs are now `https`
  * The write request for updating the website requires the credentials again. Not sure why, because there is a Cookie Manager.

### CODE REVIEW

**Comment by splitbrain** [comment]
Hmm, something's weird here. Because for writing, we do two requests.

The first opens the page in editing mode with provided credentials. It locks the page, logs the user in and returns the required CSRF token we need in the second step. It should set at least two cookies: the login info and the sessionID

The second step is writing the page. It will fail when you're not logged in or the CSRF token is wrong. The CSRF token depends on the session ID. So it should fail if either of the two cookies are missing.

So apparently the cookie jar works half?

**Comment by gamma** [comment]
Sounds like I should check the cookie jar? :)

**Comment by splitbrain** [comment]
Here's the bug: rsonghuster/phprequest#1

**Comment by gamma** [comment]
Not sure if that will ever get fixed. How about forking + fixing?

**Pull request merged**
